create extension if not exists pgcrypto;

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  unique(user_id, word)
);

create table if not exists public.attempts (
  event_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  result text not null check (result in ('lido','nao')),
  who text not null check (who in ('gabriela','adulto')),
  duration_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  case_mode text not null default 'lower' check (case_mode in ('lower','upper')),
  adaptive boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.words enable row level security;
alter table public.attempts enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "words own rows" on public.words;
drop policy if exists "attempts own rows" on public.attempts;
drop policy if exists "settings own row" on public.app_settings;

create policy "words own rows" on public.words for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "attempts own rows" on public.attempts for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "settings own row" on public.app_settings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.words to authenticated;
grant select, insert, update, delete on public.attempts to authenticated;
grant select, insert, update, delete on public.app_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create index if not exists attempts_user_created_idx on public.attempts(user_id, created_at);
create index if not exists attempts_user_word_idx on public.attempts(user_id, word);
