const K='gabriela_leitura_github_v2';
const BANK_K='gabriela_banco_2000_v1';
const BANK_SOURCE='https://raw.githubusercontent.com/fserb/pt-br/master/icf';
const starter=['pato','gato','bola','mesa','sol','mar','flor','papel','festa','porta','carta','vento','campo','filme','prato','preto','primo','fruta','bruxa','braço','bloco','planta','trigo','grito','cravo','claro','chuva','chave','ninho','banho','palha','folha','carro','terra','queijo','guerra','quadro','grande','branco','triste','estrela','presente','problema','criança'];
const blocked=new Set(('merda porra puta sexo sexual foder caralho assassino assassinato homicídio suicídio droga drogas arma armas sangue matar matou morte morto morta mortos matando mataram violência ataque bomba explosão tiro atirou atirar inferno idiota idiotas imbecil babaca vadia maldito maldita gay nudez álcool cerveja vinho presidente governo política policial polícia prisão tribunal cadáver câncer jesus deus satanás john michael david george mike james peter paul mary sarah alex jim henry walter william susan emma claire laura alice').split(' '));
const patternDefs=[
 {key:'ccvR',label:'encontro consonantal com R',re:/(?:br|cr|dr|fr|gr|pr|tr|vr)[aáâãeéêiíoóôõuú]/i},
 {key:'ccvL',label:'encontro consonantal com L',re:/(?:bl|cl|fl|gl|pl)[aáâãeéêiíoóôõuú]/i},
 {key:'cvc',label:'sílaba fechada aproximada',re:/[bcdfgjklmnpqrstvwxyz][aáâãeéêiíoóôõuú][rlsmn](?:$|[bcdfgjklmnpqrstvwxyz])/i},
 {key:'cedilha',label:'ç',re:/ç/i},{key:'ch',label:'CH',re:/ch/i},{key:'lh',label:'LH',re:/lh/i},{key:'nh',label:'NH',re:/nh/i},{key:'rr',label:'RR',re:/rr/i},{key:'ss',label:'SS',re:/ss/i},{key:'qu',label:'QU',re:/qu[ei]/i},{key:'gu',label:'GU',re:/gu[ei]/i},{key:'nasal',label:'nasalização',re:/(?:ão|õe|ãe|am|em|en|an|on|un)/i},{key:'accent',label:'acentuação',re:/[áàâãéêíóôõú]/i},{key:'long',label:'palavra longa',test:w=>w.length>=8}
];
function patternsOf(w){return patternDefs.filter(p=>p.test?p.test(w):p.re.test(w)).map(p=>p.key)}
function labelOf(k){return patternDefs.find(p=>p.key===k)?.label||k}
function migrate(raw){let base=raw&&Array.isArray(raw.words)?raw:{words:starter.map(w=>({w,history:[],source:'manual'})),settings:{caseMode:'lower',adaptive:true}};base.words=(base.words||[]).map(x=>({w:String(x.w||x.word||'').toLowerCase(),history:(x.history||[]).map(h=>({...h,durationMs:Number(h.durationMs)||Number(h.latencyMs)||null})),source:x.source||'manual'})).filter(x=>x.w);base.settings=base.settings||{};if(!base.settings.caseMode)base.settings.caseMode='lower';if(typeof base.settings.adaptive!=='boolean')base.settings.adaptive=true;return base}
function load(){for(const key of [K,'gabriela_leitura_github_v1','gabriela_github_v1','gabriela_leitura_v3','gabriela_leitura_v2','gabriela_leitura_v1']){try{let x=localStorage.getItem(key);if(x)return migrate(JSON.parse(x))}catch(e){}}return migrate(null)}
let db=load(),bank=[],queue=[],i=0,ok=0,no=0,score=0,shownAt=0,hintTimer=null,sessionTimes=[],vq=[],vi=0,vShownAt=0,vHintTimer=null,sort={col:'difficulty',dir:'desc'};
function save(){localStorage.setItem(K,JSON.stringify(db));render()}
function ch(w){return w.history.filter(x=>x.who==='gabriela')}
function hits(w){return ch(w).filter(x=>x.result==='lido').length}
function misses(w){return ch(w).filter(x=>x.result==='nao').length}
function last(w){let h=ch(w);return h.length?h[h.length-1].date:''}
function latest(w){let h=ch(w);return h[h.length-1]||null}
function learned(w){return hits(w)>0}
function cappedSec(ms){return Math.min(60,Math.max(.2,(Number(ms)||0)/1000))}
function recentTimes(w){return ch(w).filter(x=>x.durationMs).slice(-5).map(x=>cappedSec(x.durationMs))}
function avgTime(w){let a=recentTimes(w);return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function allSuccessfulSecPerChar(){let vals=[];db.words.forEach(w=>ch(w).slice(-5).forEach(h=>{if(h.result==='lido'&&h.durationMs)vals.push(cappedSec(h.durationMs)/Math.max(3,w.w.length))}));return vals.slice(-150).sort((a,b)=>a-b)}
function baselinePerChar(){let a=allSuccessfulSecPerChar();if(!a.length)return .75;return a[Math.floor(a.length/2)]}
function difficulty(w){let h=ch(w),n=h.length;if(!n)return 25;let miss=misses(w)/n,rt=avgTime(w),base=baselinePerChar()*Math.max(3,w.w.length),ratio=rt?rt/base:1,lat=Math.max(0,Math.min(1,(ratio-.75)/1.75)),recent=latest(w)?.result==='nao'?1:0,score=(.55*lat+.35*miss+.10*recent)*100;return Math.round(score)}
function progress(){let total=db.words.length,learn=db.words.filter(learned).length;return{total,learn,pct:total?Math.round(learn/total*100):0}}
function totalAttempts(){return db.words.reduce((s,w)=>s+ch(w).length,0)}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function patternStats(){let map={};for(const p of patternDefs)map[p.key]={key:p.key,label:p.label,weighted:0,weight:0,words:0};db.words.forEach(w=>{let n=ch(w).length;if(!n)return;let d=difficulty(w);patternsOf(w.w).forEach(k=>{let o=map[k];o.weighted+=d*Math.min(n,5);o.weight+=Math.min(n,5);o.words++})});return Object.values(map).filter(x=>x.weight>=3).map(x=>({...x,score:Math.round(x.weighted/x.weight)})).sort((a,b)=>b.score-a.score)}
function targetPatterns(){return patternStats().filter(x=>x.score>=30).slice(0,3).map(x=>x.key)}
function safeBankWord(w){w=w.trim().toLowerCase();if(w.length<3||w.length>12)return false;if(blocked.has(w))return false;if(!/^[a-záàâãéêíóôõúç]+$/i.test(w))return false;if(/^(www|http|html|km|fbi|tv)$/.test(w))return false;return true}
async function loadBank(force=false){bankStatus.textContent='Carregando banco...';try{if(!force){let c=JSON.parse(localStorage.getItem(BANK_K)||'null');if(Array.isArray(c)&&c.length>=1800){bank=c.slice(0,2000);bankStatus.textContent='Banco carregado do aparelho.';render();return}}let r=await fetch(BANK_SOURCE,{cache:'force-cache'});if(!r.ok)throw new Error('falha');let txt=await r.text(),seen=new Set(),arr=[];for(const line of txt.split(/\r?\n/)){let w=line.split(',')[0]?.trim().toLowerCase();if(!w||seen.has(w)||!safeBankWord(w))continue;seen.add(w);arr.push(w);if(arr.length>=2000)break}bank=arr;localStorage.setItem(BANK_K,JSON.stringify(bank));bankStatus.textContent=`Banco carregado com ${bank.length} palavras.`;render()}catch(e){try{let c=JSON.parse(localStorage.getItem(BANK_K)||'[]');bank=Array.isArray(c)?c:[]}catch{bank=[]}bankStatus.textContent=bank.length?`Usando banco salvo com ${bank.length} palavras.`:'Não foi possível carregar o banco agora. O app continua funcionando com as palavras já cadastradas.';render()}}
function addAdaptiveWords(n){if(!db.settings.adaptive||totalAttempts()<20||!bank.length||n<=0)return[];let existing=new Set(db.words.map(x=>x.w)),targets=targetPatterns(),candidates=bank.filter(w=>!existing.has(w));if(targets.length){let matched=candidates.filter(w=>patternsOf(w).some(k=>targets.includes(k)));if(matched.length>=n)candidates=matched}let picked=candidates.slice(0,Math.max(n*8,30));picked=shuffle(picked).slice(0,n);picked.forEach(w=>db.words.push({w,history:[],source:'bank'}));if(picked.length)localStorage.setItem(K,JSON.stringify(db));return picked.map(w=>db.words.find(x=>x.w===w))}
function makeQueue(n){let newN=db.settings.adaptive&&totalAttempts()>=20?Math.min(2,Math.max(1,Math.round(n*.2))):0;let newItems=addAdaptiveWords(newN),remaining=Math.max(0,n-newItems.length),existing=db.words.filter(w=>!newItems.includes(w));let hard=[...existing].sort((a,b)=>difficulty(b)-difficulty(a)),hardN=Math.ceil(remaining*.7),q=[...hard.slice(0,hardN),...shuffle(hard.slice(hardN)).slice(0,remaining-hardN),...newItems];let seen=new Set();q=q.filter(x=>!seen.has(x.w)&&seen.add(x.w));if(q.length<n)q.push(...shuffle(db.words.filter(x=>!seen.has(x.w))).slice(0,n-q.length));return shuffle(q.slice(0,Math.min(n,db.words.length)))}
function fmt(x){return x?new Date(x).toLocaleString('pt-BR'):'—'}
function applyCase(){let m=db.settings.caseMode==='upper'?'uppercase':'lowercase';document.documentElement.style.setProperty('--wordcase',m);caseMode.value=db.settings.caseMode;adaptiveMode.checked=!!db.settings.adaptive}
function render(){applyCase();let p=progress();pPct.textContent=p.pct+'%';pLearned.textContent=p.learn;pTotal.textContent=p.total;pBank.textContent=bank.length;bankCount.textContent=bank.length;attemptCount.textContent=totalAttempts();baselineSec.textContent=(baselinePerChar()*5).toFixed(1)+' s';newWordsCount.textContent=db.words.filter(w=>w.source==='bank').length;renderPatterns();renderTable()}
function renderPatterns(){let ps=patternStats().slice(0,6);patterns.innerHTML='';if(!ps.length){patterns.innerHTML='<div class="muted">Ainda não há dados suficientes.</div>';return}ps.forEach(p=>{let div=document.createElement('div');div.className='patternItem';div.innerHTML=`<div><b>${p.label}</b><div class="muted small">${p.words} palavra(s) observada(s)</div><div class="meter"><span style="width:${Math.min(100,p.score)}%"></span></div></div><div class="difficulty ${p.score>=60?'dHigh':p.score>=35?'dMid':'dLow'}">${p.score}</div>`;patterns.appendChild(div)})}
function renderTable(){let rows=[...db.words],d=sort.dir==='asc'?1:-1;rows.sort((a,b)=>{let A,B;if(sort.col==='word')return a.w.localeCompare(b.w,'pt-BR')*d;if(sort.col==='hits'){A=hits(a);B=hits(b)}else if(sort.col==='misses'){A=misses(a);B=misses(b)}else if(sort.col==='time'){A=avgTime(a);B=avgTime(b)}else if(sort.col==='difficulty'){A=difficulty(a);B=difficulty(b)}else{A=last(a)||'';B=last(b)||''}return A<B?-d:A>B?d:a.w.localeCompare(b.w,'pt-BR')});tbody.innerHTML='';rows.forEach(w=>{let di=difficulty(w),tags=patternsOf(w.w).map(k=>`<span class="tag">${labelOf(k)}</span>`).join('');let tr=document.createElement('tr');tr.innerHTML=`<td style="text-transform:var(--wordcase)"><b>${w.w}</b>${w.source==='bank'?'<div class="small muted">banco adaptativo</div>':''}</td><td class="ok">${hits(w)}</td><td class="no">${misses(w)}</td><td>${avgTime(w)?avgTime(w).toFixed(1)+' s':'—'}</td><td class="difficulty ${di>=60?'dHigh':di>=35?'dMid':'dLow'}">${di}</td><td>${tags||'<span class="muted small">simples</span>'}</td><td>${fmt(last(w))}</td>`;tbody.appendChild(tr)})}
function scheduleHint(el,timerName){clearTimeout(timerName==='main'?hintTimer:vHintTimer);let id=setTimeout(()=>{el.textContent='Tudo bem se estiver difícil. Pode marcar “Não li”.'},12000);if(timerName==='main')hintTimer=id;else vHintTimer=id}
function show(){clearTimeout(hintTimer);hint.textContent='';if(i>=queue.length)return finish();word.textContent=queue[i].w;count.textContent=`${i+1} de ${queue.length}`;scoreTop.textContent='Pontuação: '+score;bar.style.width=(i/queue.length*100)+'%';shownAt=performance.now();scheduleHint(hint,'main')}
function finish(){clearTimeout(hintTimer);play.classList.add('hidden');done.classList.remove('hidden');let p=progress(),avg=sessionTimes.length?sessionTimes.reduce((s,x)=>s+x,0)/sessionTimes.length:0;doneTxt.textContent=`Pontuação da sessão: ${score}`;doneOk.textContent=ok;doneNo.textContent=no;doneAvg.textContent=avg.toFixed(1)+' s';donePct.textContent=p.pct+'%';celeTxt.textContent=`Você leu ${ok} de ${queue.length} palavra(s).`;celeScore.textContent='Pontuação: '+score;cele.classList.remove('hidden')}
startBtn.onclick=()=>{let n=Math.max(1,Math.min(50,+size.value||10));queue=makeQueue(n);i=ok=no=score=0;sessionTimes=[];start.classList.add('hidden');done.classList.add('hidden');play.classList.remove('hidden');show()};
document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{let r=b.dataset.result,duration=Math.round(performance.now()-shownAt);queue[i].history.push({date:new Date().toISOString(),result:r,who:'gabriela',durationMs:duration});sessionTimes.push(cappedSec(duration));if(r==='lido'){ok++;score+=10}else no++;save();i++;show()});
again.onclick=()=>{done.classList.add('hidden');start.classList.remove('hidden')};closeCele.onclick=()=>cele.classList.add('hidden');
addBtn.onclick=()=>{let items=newWords.value.split(/[\n,;]+/).map(x=>x.trim().toLowerCase()).filter(Boolean),seen=new Set(db.words.map(x=>x.w)),c=0;items.forEach(w=>{if(!seen.has(w)){db.words.push({w,history:[],source:'manual'});seen.add(w);c++}});newWords.value='';addMsg.textContent=c+' palavra(s) adicionada(s).';save()};
caseMode.onchange=e=>{db.settings.caseMode=e.target.value;save()};adaptiveMode.onchange=e=>{db.settings.adaptive=e.target.checked;save()};reloadBank.onclick=()=>loadBank(true);
document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{let c=th.dataset.sort;if(sort.col===c)sort.dir=sort.dir==='asc'?'desc':'asc';else{sort.col=c;sort.dir=c==='word'?'asc':'desc'}renderTable()});
verifyBtn.onclick=()=>{vq=[...db.words].sort((a,b)=>difficulty(b)-difficulty(a));vi=0;verify.classList.remove('hidden');showV()};
function showV(){clearTimeout(vHintTimer);vHint.textContent='';if(!vq[vi]){verify.classList.add('hidden');return}vWord.textContent=vq[vi].w;vShownAt=performance.now();scheduleHint(vHint,'verify')}
document.querySelectorAll('[data-vresult]').forEach(b=>b.onclick=()=>{if(!vq[vi])return;let duration=Math.round(performance.now()-vShownAt);vq[vi].history.push({date:new Date().toISOString(),result:b.dataset.vresult,who:'adulto',durationMs:duration});save();vi++;showV()});stopV.onclick=()=>{clearTimeout(vHintTimer);verify.classList.add('hidden')};
exportBtn.onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup_gabriela.json';a.click()};importBtn.onclick=()=>file.click();file.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=migrate(JSON.parse(r.result));save();alert('Backup restaurado')}catch{alert('Arquivo inválido')}};r.readAsText(f)};
document.querySelectorAll('[data-view]').forEach(t=>t.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(t.dataset.view).classList.remove('hidden')});
render();loadBank(false);