const K='gabriela_leitura_github_v3';
const CLOUD_K='gabriela_supabase_config_v1';
const BANK_K='gabriela_banco_2000_v1';
const BANK_SOURCE='https://raw.githubusercontent.com/fserb/pt-br/master/icf';
const starter=['pato','gato','bola','mesa','sol','mar','flor','papel','festa','porta','carta','vento','campo','filme','prato','preto','primo','fruta','bruxa','braço','bloco','planta','trigo','grito','cravo','claro','chuva','chave','ninho','banho','palha','folha','carro','terra','queijo','guerra','quadro','grande','branco','triste','estrela','presente','problema','criança'];
const blocked=new Set(('merda porra puta sexo sexual foder caralho assassino assassinato homicídio suicídio droga drogas arma armas sangue matar matou morte morto morta mortos matando mataram violência ataque bomba explosão tiro atirou atirar inferno idiota idiotas imbecil babaca vadia maldito maldita nudez álcool cerveja vinho presidente governo política policial polícia prisão tribunal cadáver câncer').split(' '));
const patternDefs=[
 {key:'ccvR',label:'encontro consonantal com R',re:/(?:br|cr|dr|fr|gr|pr|tr|vr)[aáâãeéêiíoóôõuú]/i},
 {key:'ccvL',label:'encontro consonantal com L',re:/(?:bl|cl|fl|gl|pl)[aáâãeéêiíoóôõuú]/i},
 {key:'cvc',label:'sílaba fechada aproximada',re:/[bcdfgjklmnpqrstvwxyz][aáâãeéêiíoóôõuú][rlsmn](?:$|[bcdfgjklmnpqrstvwxyz])/i},
 {key:'cedilha',label:'ç',re:/ç/i},{key:'ch',label:'CH',re:/ch/i},{key:'lh',label:'LH',re:/lh/i},{key:'nh',label:'NH',re:/nh/i},{key:'rr',label:'RR',re:/rr/i},{key:'ss',label:'SS',re:/ss/i},{key:'qu',label:'QU',re:/qu[ei]/i},{key:'gu',label:'GU',re:/gu[ei]/i},{key:'nasal',label:'nasalização',re:/(?:ão|õe|ãe|am|em|en|an|on|un)/i},{key:'accent',label:'acentuação',re:/[áàâãéêíóôõú]/i},{key:'long',label:'palavra longa',test:w=>w.length>=8}
];
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random().toString(36).slice(2)}`}
function patternsOf(w){return patternDefs.filter(p=>p.test?p.test(w):p.re.test(w)).map(p=>p.key)}
function labelOf(k){return patternDefs.find(p=>p.key===k)?.label||k}
function fresh(){return{words:starter.map(w=>({w,history:[],source:'manual'})),settings:{caseMode:'lower',adaptive:true}}}
function normalize(raw){let base=raw&&Array.isArray(raw.words)?raw:fresh();base.words=(base.words||[]).map(x=>({w:String(x.w||x.word||'').trim().toLowerCase(),history:(x.history||[]).map(h=>({eventId:h.eventId||uid(),date:h.date||new Date().toISOString(),result:(h.result==='solo'||h.result==='ajuda'||h.result==='lido')?'lido':'nao',who:h.who||'gabriela',durationMs:Number(h.durationMs)||Number(h.latencyMs)||null,synced:!!h.synced})),source:x.source||'manual'})).filter(x=>x.w);base.settings=base.settings||{};base.settings.caseMode=base.settings.caseMode==='upper'?'upper':'lower';base.settings.adaptive=base.settings.adaptive!==false;return base}
function load(){for(const key of [K,'gabriela_leitura_github_v2','gabriela_leitura_github_v1','gabriela_github_v1','gabriela_leitura_v3','gabriela_leitura_v2','gabriela_leitura_v1']){try{let x=localStorage.getItem(key);if(x)return normalize(JSON.parse(x))}catch(e){}}return fresh()}
let db=load(),bank=[],queue=[],i=0,ok=0,no=0,score=0,shownAt=0,hintTimer=null,sessionTimes=[],vq=[],vi=0,vShownAt=0,vHintTimer=null,sort={col:'difficulty',dir:'desc'};
let sb=null,sbUser=null,syncBusy=false;
function persist(){localStorage.setItem(K,JSON.stringify(db))}
function save(){persist();render();if(sbUser)syncCloud(false)}
function ch(w){return w.history.filter(x=>x.who==='gabriela')}
function hits(w){return ch(w).filter(x=>x.result==='lido').length}
function misses(w){return ch(w).filter(x=>x.result==='nao').length}
function last(w){let h=ch(w);return h.length?h[h.length-1].date:''}
function latest(w){let h=ch(w);return h[h.length-1]||null}
function learned(w){return hits(w)>0}
function cappedSec(ms){return Math.min(60,Math.max(.2,(Number(ms)||0)/1000))}
function recentTimes(w){return ch(w).filter(x=>x.durationMs).slice(-5).map(x=>cappedSec(x.durationMs))}
function avgTime(w){let a=recentTimes(w);return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function allSuccessfulSecPerChar(){let vals=[];db.words.forEach(w=>ch(w).slice(-5).forEach(h=>{if(h.result==='lido'&&h.durationMs)vals.push(cappedSec(h.durationMs)/Math.max(3,w.w.length))}));return vals.slice(-150).sort((a,b)=>a-b)}
function baselinePerChar(){let a=allSuccessfulSecPerChar();if(!a.length)return .75;return a[Math.floor(a.length/2)]}
function difficulty(w){let h=ch(w),n=h.length;if(!n)return 25;let miss=misses(w)/n,rt=avgTime(w),base=baselinePerChar()*Math.max(3,w.w.length),ratio=rt?rt/base:1,lat=Math.max(0,Math.min(1,(ratio-.75)/1.75)),recent=latest(w)?.result==='nao'?1:0;return Math.round((.55*lat+.35*miss+.10*recent)*100)}
function progress(){let total=db.words.length,learn=db.words.filter(learned).length;return{total,learn,pct:total?Math.round(learn/total*100):0}}
function totalAttempts(){return db.words.reduce((s,w)=>s+ch(w).length,0)}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function patternStats(){let map={};for(const p of patternDefs)map[p.key]={key:p.key,label:p.label,weighted:0,weight:0,words:0};db.words.forEach(w=>{let n=ch(w).length;if(!n)return;let d=difficulty(w);patternsOf(w.w).forEach(k=>{let o=map[k];o.weighted+=d*Math.min(n,5);o.weight+=Math.min(n,5);o.words++})});return Object.values(map).filter(x=>x.weight>=3).map(x=>({...x,score:Math.round(x.weighted/x.weight)})).sort((a,b)=>b.score-a.score)}
function targetPatterns(){return patternStats().filter(x=>x.score>=30).slice(0,3).map(x=>x.key)}
function safeBankWord(w){w=w.trim().toLowerCase();if(w.length<3||w.length>12)return false;if(blocked.has(w))return false;if(!/^[a-záàâãéêíóôõúç]+$/i.test(w))return false;if(/^(www|http|html|km|fbi|tv)$/.test(w))return false;return true}
async function loadBank(force=false){bankStatus.textContent='Carregando banco...';try{if(!force){let c=JSON.parse(localStorage.getItem(BANK_K)||'null');if(Array.isArray(c)&&c.length>=1800){bank=c.slice(0,2000);bankStatus.textContent='Banco carregado do aparelho.';render();return}}let r=await fetch(BANK_SOURCE,{cache:'force-cache'});if(!r.ok)throw new Error('falha');let txt=await r.text(),seen=new Set(),arr=[];for(const line of txt.split(/\r?\n/)){let w=line.split(',')[0]?.trim().toLowerCase();if(!w||seen.has(w)||!safeBankWord(w))continue;seen.add(w);arr.push(w);if(arr.length>=2000)break}bank=arr;localStorage.setItem(BANK_K,JSON.stringify(bank));bankStatus.textContent=`Banco carregado com ${bank.length} palavras.`;render()}catch(e){try{let c=JSON.parse(localStorage.getItem(BANK_K)||'[]');bank=Array.isArray(c)?c:[]}catch{bank=[]}bankStatus.textContent=bank.length?`Usando banco salvo com ${bank.length} palavras.`:'Não foi possível carregar o banco agora. O app continua funcionando com as palavras já cadastradas.';render()}}
function addAdaptiveWords(n){if(!db.settings.adaptive||totalAttempts()<20||!bank.length||n<=0)return[];let existing=new Set(db.words.map(x=>x.w)),targets=targetPatterns(),candidates=bank.filter(w=>!existing.has(w));if(targets.length){let matched=candidates.filter(w=>patternsOf(w).some(k=>targets.includes(k)));if(matched.length>=n)candidates=matched}let picked=shuffle(candidates.slice(0,Math.max(n*10,60))).slice(0,n);picked.forEach(w=>db.words.push({w,history:[],source:'bank'}));persist();return picked.map(w=>db.words.find(x=>x.w===w))}
function makeQueue(n){let newN=db.settings.adaptive&&totalAttempts()>=20?Math.min(2,Math.max(1,Math.round(n*.2))):0;let newItems=addAdaptiveWords(newN),remaining=Math.max(0,n-newItems.length),existing=db.words.filter(w=>!newItems.includes(w));let hard=[...existing].sort((a,b)=>difficulty(b)-difficulty(a)),hardN=Math.ceil(remaining*.7),q=[...hard.slice(0,hardN),...shuffle(hard.slice(hardN)).slice(0,remaining-hardN),...newItems];let seen=new Set();q=q.filter(x=>!seen.has(x.w)&&seen.add(x.w));if(q.length<n)q.push(...shuffle(db.words.filter(x=>!seen.has(x.w))).slice(0,n-q.length));return shuffle(q.slice(0,Math.min(n,db.words.length)))}
function fmt(x){return x?new Date(x).toLocaleString('pt-BR'):'—'}
function applyCase(){document.documentElement.style.setProperty('--wordcase',db.settings.caseMode==='upper'?'uppercase':'lowercase');caseMode.value=db.settings.caseMode;adaptiveMode.checked=!!db.settings.adaptive}
function render(){applyCase();let p=progress();pPct.textContent=p.pct+'%';pLearned.textContent=p.learn;pTotal.textContent=p.total;pBank.textContent=bank.length;bankCount.textContent=bank.length;attemptCount.textContent=totalAttempts();baselineSec.textContent=(baselinePerChar()*5).toFixed(1)+' s';newWordsCount.textContent=db.words.filter(w=>w.source==='bank').length;renderPatterns();renderTable();renderCloudState()}
function renderPatterns(){let ps=patternStats().slice(0,6);patterns.innerHTML='';if(!ps.length){patterns.innerHTML='<div class="muted">Ainda não há dados suficientes.</div>';return}ps.forEach(p=>{let div=document.createElement('div');div.className='patternItem';div.innerHTML=`<div><b>${p.label}</b><div class="muted small">${p.words} palavra(s) observada(s)</div><div class="meter"><span style="width:${Math.min(100,p.score)}%"></span></div></div><div class="difficulty ${p.score>=60?'dHigh':p.score>=35?'dMid':'dLow'}">${p.score}</div>`;patterns.appendChild(div)})}
function renderTable(){let rows=[...db.words],d=sort.dir==='asc'?1:-1;rows.sort((a,b)=>{let A,B;if(sort.col==='word')return a.w.localeCompare(b.w,'pt-BR')*d;if(sort.col==='hits'){A=hits(a);B=hits(b)}else if(sort.col==='misses'){A=misses(a);B=misses(b)}else if(sort.col==='time'){A=avgTime(a);B=avgTime(b)}else if(sort.col==='difficulty'){A=difficulty(a);B=difficulty(b)}else{A=last(a)||'';B=last(b)||''}return A<B?-d:A>B?d:a.w.localeCompare(b.w,'pt-BR')});tbody.innerHTML='';rows.forEach(w=>{let di=difficulty(w),tg=patternsOf(w.w).map(k=>`<span class="tag">${labelOf(k)}</span>`).join('');let tr=document.createElement('tr');tr.innerHTML=`<td style="text-transform:var(--wordcase)"><b>${w.w}</b>${w.source==='bank'?'<div class="small muted">banco adaptativo</div>':''}</td><td class="ok">${hits(w)}</td><td class="no">${misses(w)}</td><td>${avgTime(w)?avgTime(w).toFixed(1)+' s':'—'}</td><td><span class="difficulty ${di>=60?'dHigh':di>=35?'dMid':'dLow'}">${di}</span></td><td>${tg||'<span class="muted small">simples</span>'}</td><td>${fmt(last(w))}</td>`;tbody.appendChild(tr)})}
function scheduleHint(el,which){clearTimeout(which==='main'?hintTimer:vHintTimer);let id=setTimeout(()=>{el.textContent='Tudo bem se estiver difícil. Pode marcar “Não li”.'},12000);if(which==='main')hintTimer=id;else vHintTimer=id}
function show(){clearTimeout(hintTimer);hint.textContent='';if(i>=queue.length)return finish();word.textContent=queue[i].w;count.textContent=`${i+1} de ${queue.length}`;scoreTop.textContent='Pontuação: '+score;bar.style.width=(i/queue.length*100)+'%';shownAt=performance.now();scheduleHint(hint,'main')}
function finish(){clearTimeout(hintTimer);play.classList.add('hidden');done.classList.remove('hidden');let p=progress(),avg=sessionTimes.length?sessionTimes.reduce((s,x)=>s+x,0)/sessionTimes.length:0;doneTxt.textContent=`Pontuação da sessão: ${score}`;doneOk.textContent=ok;doneNo.textContent=no;doneAvg.textContent=avg.toFixed(1)+' s';donePct.textContent=p.pct+'%';celeTxt.textContent=`Você leu ${ok} de ${queue.length} palavra(s).`;celeScore.textContent='Pontuação: '+score;cele.classList.remove('hidden')}
function addAttempt(wordObj,who,result,duration){wordObj.history.push({eventId:uid(),date:new Date().toISOString(),result,who,durationMs:duration,synced:false})}
function cloudConfig(){try{return JSON.parse(localStorage.getItem(CLOUD_K)||'{}')}catch{return{}}}
function setCloudConfig(url,key){localStorage.setItem(CLOUD_K,JSON.stringify({url:url.trim(),key:key.trim()}))}
function initSupabase(){const cfg=cloudConfig();sbUrl.value=cfg.url||'';sbKey.value=cfg.key||'';if(!cfg.url||!cfg.key||!window.supabase){sb=null;sbUser=null;renderCloudState();return false}try{sb=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});sb.auth.getSession().then(({data})=>{sbUser=data.session?.user||null;renderCloudState();if(sbUser)syncCloud(true)});sb.auth.onAuthStateChange((_event,session)=>{sbUser=session?.user||null;renderCloudState();if(sbUser)syncCloud(true)});return true}catch(e){sb=null;sbUser=null;cloudMsg.textContent='Não foi possível iniciar a conexão com o Supabase.';renderCloudState();return false}}
function renderCloudState(){if(sbUser){cloudBadge.textContent='Nuvem conectada';cloudBadge.className='cloudBadge online';syncState.textContent='conectada';sbSync.classList.remove('hidden');sbLogout.classList.remove('hidden');sbLogin.classList.add('hidden');sbSignup.classList.add('hidden')}else{cloudBadge.textContent=sb?'Nuvem pronta para login':'Somente neste aparelho';cloudBadge.className='cloudBadge offline';syncState.textContent=sb?'aguardando login':'não configurada';sbSync.classList.add('hidden');sbLogout.classList.add('hidden');sbLogin.classList.remove('hidden');sbSignup.classList.remove('hidden')}}
async function cloudLogin(){if(!sb&& !initSupabase())return;cloudMsg.textContent='Entrando...';let {data,error}=await sb.auth.signInWithPassword({email:sbEmail.value.trim(),password:sbPassword.value});if(error){cloudMsg.textContent='Erro ao entrar: '+error.message;return}sbUser=data.user;sbPassword.value='';cloudMsg.textContent='Conectado. Sincronizando dados...';await syncCloud(true)}
async function cloudSignup(){if(!sb&& !initSupabase())return;cloudMsg.textContent='Criando conta...';let {data,error}=await sb.auth.signUp({email:sbEmail.value.trim(),password:sbPassword.value});if(error){cloudMsg.textContent='Erro ao criar conta: '+error.message;return}sbUser=data.user||null;sbPassword.value='';cloudMsg.textContent=data.session?'Conta criada e conectada.':'Conta criada. Se o projeto exigir confirmação por e mail, confirme antes de entrar.';if(sbUser)await syncCloud(true)}
async function cloudLogout(){if(sb)await sb.auth.signOut();sbUser=null;renderCloudState();cloudMsg.textContent='Sessão da nuvem encerrada neste aparelho.'}
async function syncCloud(showMessage=true){if(!sb||!sbUser||syncBusy)return;syncBusy=true;if(showMessage)cloudMsg.textContent='Sincronizando...';try{
  const uidv=sbUser.id;
  let wordRows=db.words.map(w=>({user_id:uidv,word:w.w,source:w.source||'manual'}));
  if(wordRows.length){let {error}=await sb.from('words').upsert(wordRows,{onConflict:'user_id,word'});if(error)throw error}
  let unsynced=[];db.words.forEach(w=>w.history.forEach(h=>{if(!h.synced)unsynced.push({event_id:h.eventId,user_id:uidv,word:w.w,result:h.result,who:h.who,duration_ms:h.durationMs||null,created_at:h.date})}));
  if(unsynced.length){for(let start=0;start<unsynced.length;start+=300){let {error}=await sb.from('attempts').upsert(unsynced.slice(start,start+300),{onConflict:'event_id'});if(error)throw error}}
  let {error:setErr}=await sb.from('app_settings').upsert({user_id:uidv,case_mode:db.settings.caseMode,adaptive:db.settings.adaptive},{onConflict:'user_id'});if(setErr)throw setErr;
  let [{data:cloudWords,error:wErr},{data:cloudAttempts,error:aErr},{data:cloudSettings,error:sErr}]=await Promise.all([
    sb.from('words').select('word,source').eq('user_id',uidv),
    sb.from('attempts').select('event_id,word,result,who,duration_ms,created_at').eq('user_id',uidv).order('created_at',{ascending:true}),
    sb.from('app_settings').select('case_mode,adaptive').eq('user_id',uidv).maybeSingle()
  ]);
  if(wErr)throw wErr;if(aErr)throw aErr;if(sErr)throw sErr;
  const map=new Map(db.words.map(w=>[w.w,w]));
  (cloudWords||[]).forEach(r=>{if(!map.has(r.word)){let obj={w:r.word,history:[],source:r.source||'cloud'};db.words.push(obj);map.set(r.word,obj)}});
  const localEvents=new Set();db.words.forEach(w=>w.history.forEach(h=>localEvents.add(h.eventId)));
  (cloudAttempts||[]).forEach(r=>{if(localEvents.has(r.event_id))return;let w=map.get(r.word);if(!w){w={w:r.word,history:[],source:'cloud'};db.words.push(w);map.set(r.word,w)}w.history.push({eventId:r.event_id,date:r.created_at,result:r.result,who:r.who,durationMs:r.duration_ms,synced:true});localEvents.add(r.event_id)});
  db.words.forEach(w=>w.history.forEach(h=>h.synced=true));
  if(cloudSettings){db.settings.caseMode=cloudSettings.case_mode==='upper'?'upper':'lower';db.settings.adaptive=cloudSettings.adaptive!==false}
  persist();render();if(showMessage)cloudMsg.textContent='Sincronização concluída.';
}catch(e){cloudMsg.textContent='Falha ao sincronizar. Os dados continuam salvos neste aparelho. '+(e.message||'');}finally{syncBusy=false}}
startBtn.onclick=()=>{let n=Math.max(1,Math.min(50,+size.value||10));queue=makeQueue(n);i=ok=no=score=0;sessionTimes=[];start.classList.add('hidden');done.classList.add('hidden');play.classList.remove('hidden');show()};
document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{let r=b.dataset.result,duration=Math.round(performance.now()-shownAt);addAttempt(queue[i],'gabriela',r,duration);sessionTimes.push(cappedSec(duration));if(r==='lido'){ok++;score+=10}else no++;save();i++;show()});
again.onclick=()=>{done.classList.add('hidden');start.classList.remove('hidden')};closeCele.onclick=()=>cele.classList.add('hidden');
addBtn.onclick=()=>{let items=newWords.value.split(/[\n,;]+/).map(x=>x.trim().toLowerCase()).filter(Boolean),seen=new Set(db.words.map(x=>x.w)),c=0;items.forEach(w=>{if(!seen.has(w)){db.words.push({w,history:[],source:'manual'});seen.add(w);c++}});newWords.value='';addMsg.textContent=c+' palavra(s) adicionada(s).';save()};
caseMode.onchange=e=>{db.settings.caseMode=e.target.value;save()};adaptiveMode.onchange=e=>{db.settings.adaptive=e.target.checked;save()};reloadBank.onclick=()=>loadBank(true);
document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{let c=th.dataset.sort;if(sort.col===c)sort.dir=sort.dir==='asc'?'desc':'asc';else{sort.col=c;sort.dir=c==='word'?'asc':'desc'}renderTable()});
verifyBtn.onclick=()=>{vq=[...db.words].sort((a,b)=>difficulty(b)-difficulty(a));vi=0;verify.classList.remove('hidden');showV()};
function showV(){clearTimeout(vHintTimer);vHint.textContent='';if(!vq[vi]){verify.classList.add('hidden');return}vWord.textContent=vq[vi].w;vShownAt=performance.now();scheduleHint(vHint,'verify')}
document.querySelectorAll('[data-vresult]').forEach(b=>b.onclick=()=>{if(!vq[vi])return;let duration=Math.round(performance.now()-vShownAt);addAttempt(vq[vi],'adulto',b.dataset.vresult,duration);save();vi++;showV()});stopV.onclick=()=>verify.classList.add('hidden');
exportBtn.onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup_gabriela.json';a.click()};importBtn.onclick=()=>file.click();file.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=normalize(JSON.parse(r.result));save();alert('Backup restaurado')}catch{alert('Arquivo inválido')}};r.readAsText(f)};
document.querySelectorAll('[data-view]').forEach(t=>t.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(t.dataset.view).classList.remove('hidden')});
sbSave.onclick=()=>{setCloudConfig(sbUrl.value,sbKey.value);initSupabase();cloudMsg.textContent='Conexão salva neste aparelho.'};sbLogin.onclick=cloudLogin;sbSignup.onclick=cloudSignup;sbLogout.onclick=cloudLogout;sbSync.onclick=()=>syncCloud(true);
window.addEventListener('online',()=>{if(sbUser)syncCloud(false)});
loadBank(false);initSupabase();render();
